### ISSUE TITLE
"red screen of death"

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#239] opened 2019-11-22 11:27 UTC
Opening this as tracking in Slack doesn't seem like a good idea. 
Caveat: if this is solved by 1903, then no worries, just scribbling here in case it's not.

Symptom is that one or more Fluent windows become totally red and can only be fixed by killing them and/or restarting Fluent.

Anecdotally, this has been when my laptop is woken from sleep. Also, when I have more than one Fluent window, each with a number of tabs.

However, this morning, steps were:
- only one window, had weird redraw issue where about the bottom 1cm of the window wouldn't redraw.
- to try and force a redraw I minimized it.
- on restore from minimize, I had the red screen of death.

Interesting learning point: even though I couldn't see them, I was able to drag tabs out of the red screen (first one was actually by accident ;-)), so I managed to rescure all the tabs I cared about.

**Comment by peske** [comment] 2019-11-22 17:41
Interesting find is that "red screen of death" actually doesn't crash the app. Otherwise you won't be able to restore tabs from _crashed_ window. For this reason I suspect that this may be caused by https://github.com/jumptrading/FluentTerminal/issues/241. We'll see...

**Comment by mjs** [comment] 2019-12-06 19:26
@cjw296 can we close this? I think you said this seems to have been fixed.

**Closed** 2019-12-08 20:15 UTC
Labels: bug
