### ISSUE TITLE
.msi installer didn't set up ssh:// handler

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#72] opened 2019-05-09 13:33 UTC
It was left empty, setting it up by hand worked though.

**Comment by MaxRis** [comment] 2019-05-09 18:31
ssh:// should be set by call of `Add-AppxPackage` which is done from msi installer. Actually, there is no difference of mosh:// and ssh:// setup. Both specified in Package.appxmanifest and should be handled automatically by `Add-AppxPackage`.
will try to repro the issue on clean machine.

**Comment by MaxRis** [comment] 2019-05-13 09:08
was able to repro the issue. mosh:// protocol handler application is set fine, but for ssh:// Fluent Terminal doesn't appear in the list of supporting apps.

**Comment by MaxRis** [comment] 2019-05-26 11:49
@cjw296 I've run more testing and on clean Windows 10 1903 Build 18343.1 with latest available msi https://github.com/jumptrading/FluentTerminal/releases/download/1.1.152.0/FluentTerminalInstaller-v1.1.152.0-d010ddc.msi ssh:// handling by FluentTerminal works great. Both mosh and ssh handling were set automatically by installation process.
Since I'm able to repro the issue with ssh:// on older Windows 10 build, but mosh:// works good in the same time, it looks as an issue in Windows 10 internals. Hopefully, just an upgrade to newer Windows 10 build will help to not experience the issue. cc: @mjs

**Comment by daviesalex** [comment] 2019-05-26 11:56
If this works in 1903, I think we just leave it. We will likely upgrade all users to that in the Summer.

**Comment by MaxRis** [comment] 2019-05-26 12:23
In case of multiple ssh handling capable applications installed Windows offers to select Default (please look at screenshot below), but `Fluent Terminal` is available in the list of suggested apps to open ssh:// link if it's visited from the web-browser, for example.

![select-default-ssh-handler-app](https://user-images.githubusercontent.com/1928902/58381659-42a7f100-7fc8-11e9-876d-3abc9d817b71.png)

Specific protocol handling capability for any UWP app is defined in Package.appxmanifest file just with few lines:
```
<uap:Extension Category="windows.protocol">
    <uap:Protocol Name="ssh" />
</uap:Extension>
```

In theory, if above UWP mechanism to handle protocol will continue to not work good, we can try to use old one through defines in Windows Registry and possibility to call Fluent Terminal from the command line ( `flute.exe` )

**Comment by MaxRis** [comment] 2019-05-28 08:21
Going to close this Issue for now. As it was mentioned above, the issue is related to Windows internals and the new way of how UWP apps setup protocols handling. If it will appear in future, it might makes sense to implement protocol handling setup in old fashioned Windows Registry way.

**Closed by MaxRis** 2019-05-28 08:21 UTC
Labels: bug
