### ISSUE TITLE
ssh or mosh processes are not terminated on closing of tab

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#94] opened 2019-05-22 12:07 UTC
At least ssh.exe and mosh processes remain running in system even after the corresponding tab is closed by user.

The issue was noticed with Docker container initially.

**Comment by peske** [comment] 2019-06-17 17:29
I cannot reproduce this one at all. I've tried by running FT from VS, and also by running it as regular UWP app, and in both cases all underlying processes (ssh.exe, mosh.exe and mosh-client.exe) get killed when I close the tab.
@MaxRis can you provide more info? Screenshot?

**Comment by MaxRis** [comment] 2019-06-19 10:00
The issue as it is described seems is not reproducible any more, but on closing of WSL tab some spawned processes related to WSL still remain running. Most likely issue with WSL is not directly related to current issue.

**Comment by mjs** [comment] 2019-06-25 04:58
Let's close this for now then.

**Comment by mjs** [comment] 2019-07-02 01:19
I can reliably reproduce this issue. The key thing is to start the SSH session using ConPTY. When the tab is closed or FluentTerminal is closed by selecting "Exit" from the system tray right click menu, the ssh process is left behind.

The problem doesn't happen for WinPty based sessions.

Exact steps:

- Start a new SSH connection (ad hoc or profile) that uses ConPTY
- Check task manager and observe the new SSH process that is a child of FluentTerminal
- Close the tab OR right click on the system tray icon and select "Exit"
- Check task manager and see that the ssh process has been left behind

**Closed** 2019-08-20 06:02 UTC
Labels: bug, upstream
