### ISSUE TITLE
ssh://host brings up dialog rather than using current username

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#73] opened 2019-05-09 13:34 UTC
ssh://host should ssh to host using the current username, currently brings up the ssh login dialog

**Comment by peske** [comment] 2019-06-13 22:11
It's by design. If `ssh://` doesn't contain the username - "SSH Info" dialog gets opened, and "Username" field gets prefilled with actual Windows username, but the user still has a chance to change it.

It is true that such implementation introduces additional click to the workflow (clicking OK in "SSH Info" dialog), but on the other side it keeps the link usable if the username should be changed (i.e. to `root` or something).

I can change this, of course, if you guys agree that _auto-username-connect_ is a better behavior.

**Comment by daviesalex** [comment] 2019-06-14 22:16
@cjw296 has a specific workflow here that I understand. However, the usual case for a user (e.g. a home user) will be logged on as their name, and want to connect as some other user. 

I think our options are:
- Status quo. This particular use case requires I think an extra enter key (perhaps something else?)
- Do what is proposed here. ssh:// links wont work for most home users, but most enterprise users will be fine
- Make it configurable (i'm loath to make every possible workflow a option though). 

I dont feel super strongly about this. Might want to check with @cjw296 how strongly he feels about this - perhaps the impact here is more than a second enter key.

**Comment by cjw296** [comment] 2019-06-17 14:45
@daviesalex - particularly in a corporate environment, users will hopefully have the same username on local and remote machines. Even at home this is the case for me, just the username is different ;-)

We have a lot of generated ssh links that benefit from not having to have a username specified in them, the speed bump of having to hit enter feels unnecessary for most cases. If people feel strongly that they really want to be able to edit the username (and bear in mind this is only in the case where it's not specified in the link), then maybe that would be worth a config option?

I don't agree that "ssh:// links wont work for most home users", if a different username is required, it'll be specified in the url, just like the ssh client:

`ssh somehost` uses my current username in that shell
`ssh someuser@somehost` uses the username I've specified.

**Comment by mjs** [comment] 2019-06-18 10:06
My 2c is that we go with the approach @cjw296 suggests here. If the username is missing just use the current user's username. This makes some useful functionality possible in corporate environments and if someone needs a specific username they can include it in the URL.

**Comment by peske** [comment] 2019-06-23 22:21
I've solved this one by adding another settings option in Settings -> Default page: **"Auto-fallback to Windows username if a link doesn't contain it"**. If this option is set to `true` (default), the app will not show "SSH Info".
I hope that this is acceptable for all?

**Comment by cjw296** [comment] 2019-06-24 07:53
Is there a build with this implemented that I can test?

**Comment by peske** [comment] 2019-06-24 07:57
@cjw296 : Not yet. The PR (https://github.com/felixse/FluentTerminal/pull/415) waits to be merged upstream. Hopefully, we'll have it built today or tomorrow.

**Comment by peske** [comment] 2019-06-25 06:41
Done. Closing.

**Closed by peske** 2019-06-25 06:41 UTC
Labels: upstream
