### ISSUE TITLE
Selection copy/paste doesn't stop on end of the line

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#205] opened 2019-08-28 09:00 UTC
> that's what happened when I tried to copy/paste 7d8b72c16c40

![image](https://user-images.githubusercontent.com/1928902/63841302-3f3b5180-c98b-11e9-9864-57e69ae094d2.png)

**Comment by MaxRis** [comment] 2019-09-02 12:34
@cjw296 I afraid that this behavior is by design because Xterm.JS don't know when the previous line is finished or should be continued on next line.
I believe, that I have researched for reason of similar issues recently, will try to link to this Issue previous detailed findings.

As workaround, you might be able to resize the terminal window (seems, works good for me on Ubuntu with the same `docker ps` command and last column is far away from right terminal border to cause selection jumping to another line).

**Comment by MaxRis** [comment] 2019-09-02 12:43
So, it's related to the fact that XtermJS doesn't know where the terminal line really breaks.
https://github.com/jumptrading/FluentTerminal/issues/76
I would left such behavior as feature, but not as an issue :)

**Comment by cjw296** [comment] 2019-09-04 09:02
Hmm, I don't understand the "by design" or "doesn't know when the previous line is finished". Surely the previous line finishes where the previous newline is found in the shell's content?

**Comment by MaxRis** [comment] 2019-09-04 10:44
> Surely the previous line finishes where the previous newline is found in the shell's content?

XtermJS has "wrapped" line feature. Line becomes wrapped if it ends on non space character.
As I believe, currently, XtermJS and new ConPTY doesn't play well together and the issue you experienced is false positive detection of "wrapped" line.

**Comment by mjs** [comment] 2019-10-22 08:36
Won't fix.

**Closed by mjs** 2019-10-22 08:36 UTC
Labels: bug
