### ISSUE TITLE
npm install for client libraries doesn't work anymore

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#131] opened 2019-06-23 20:48 UTC
@MaxRis , after https://github.com/felixse/FluentTerminal/commit/c70061995f03c8cc812c214357a22618d60a5397, `npm install` stopped working for me. Here's the output I'm getting:
```
C:\Repos\GitHub\felixse\FluentTerminal\FluentTerminal.Client>npm install
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > node-pty@0.7.6 install C:\Users\fatdragon\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-3b19612a\node_modules\node-pty
npm ERR! prepareGitDep > node scripts/install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\fatdragon\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-3b19612a\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\fatdragon\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\fatdragon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! prepareGitDep npm WARN deprecated wreck@6.3.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! prepareGitDep npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep gyp ERR! UNCAUGHT EXCEPTION
npm ERR! prepareGitDep gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! prepareGitDep gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
npm ERR! prepareGitDep gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
npm ERR! prepareGitDep gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! prepareGitDep gyp ERR! System Windows_NT 10.0.17763
npm ERR! prepareGitDep gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fatdragon\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! prepareGitDep gyp ERR! cwd C:\Users\fatdragon\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-3b19612a\node_modules\node-pty
npm ERR! prepareGitDep gyp ERR! node -v v10.16.0
npm ERR! prepareGitDep gyp ERR! node-gyp -v v3.8.0
npm ERR! prepareGitDep gyp ERR! This is a bug in `node-gyp`.
npm ERR! prepareGitDep gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! prepareGitDep gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! prepareGitDep npm WARN xterm-addon-attach@0.1.0-beta8 requires a peer of xterm@^3.10.0 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN xterm-addon-search@0.1.0-beta4 requires a peer of xterm@^3.13.0 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN xterm-addon-web-links@0.1.0-beta6 requires a peer of xterm@^3.10.0 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 7
npm ERR! prepareGitDep npm ERR! node-pty@0.7.6 install: `node scripts/install.js`
npm ERR! prepareGitDep npm ERR! Exit status 7
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the node-pty@0.7.6 install script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\fatdragon\AppData\Roaming\npm-cache\_logs\2019-06-23T20_38_25_120Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fatdragon\AppData\Roaming\npm-cache\_logs\2019-06-23T20_38_25_498Z-debug.log
```
Here are the log files mentioned in the output above:

[2019-06-23T20_38_25_120Z-debug.log](https://github.com/jumptrading/FluentTerminal/files/3318557/2019-06-23T20_38_25_120Z-debug.log)
[2019-06-23T20_38_25_498Z-debug.log](https://github.com/jumptrading/FluentTerminal/files/3318558/2019-06-23T20_38_25_498Z-debug.log)

**Comment by peske** [comment] 2019-06-23 20:53
It looks to me that the key part is in the line `20` of the first attached log file:
```
20 silly fetchPackageMetaData error for xterm@git+https://github.com/MaxRis/xterm.js.git#3.14.1-patched premature close
```

**Comment by MaxRis** [comment] 2019-06-24 08:11
Still was not able to reproduce this locally. Curious if @mjs @felixse you guys have experienced something similar

**Comment by daviesalex** [comment] 2019-06-24 11:35
https://github.com/mattermost/mattermost-mobile/issues/2405 ?

**Comment by MaxRis** [comment] 2019-06-24 12:00
@peske `yarn` instead of `npm` works perfectly to me (and it usually worked better as well). To build it with yarn:

1. Install yarn on your system with: `npm install -g yarn`
2. cd to FT Client and delete package-lock.json.
3. run:
```cmd
yarn install
yarn run build
```

**Comment by MaxRis** [comment] 2019-06-24 22:20
@peske closing this for now.
Menno was able to confirm that npm install/build works good for him locally.
Also `yarn` instead of `npm` should work much more reliable! Please give it a try

**Closed by MaxRis** 2019-06-24 22:20 UTC
Labels: bug, upstream
