### ISSUE TITLE
[mosh] Flickering when tmux has panes

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#62] opened 2019-05-04 17:50 UTC
Tracking issue for slack discussion (video in Slack too)

**Comment by MaxRis** [comment] 2019-05-31 20:22
Seems was able to reproduce flickering stably if mosh-client is launched from `Qt Creator` IDE terminal emulator window. Under FT buggy effect appears time to time and is pretty rare.

**Comment by MaxRis** [comment] 2019-06-12 12:24
The issue is caused by `mosh-client` which puts new line character `\n` to scroll down "scrolling region".

OpenSSH instead of `\n` sends `CSI n S` sequence to scroll for `n` lines.

Current solution is to use OpenSSH's approach. Merged into `mosh-client` by https://github.com/jumptrading/mosh-windows-wrappers/pull/25

**Closed** 2019-06-12 12:31 UTC
Labels: bug, upstream

**Comment by MaxRis** [comment] 2019-06-12 14:50
Should be resolved in https://github.com/jumptrading/FluentTerminal/releases/download/1.1.182.0/FluentTerminalInstaller-v1.1.182.0-6d0f063.msi

**Comment by MaxRis** [comment] 2019-06-12 21:23
Samples of data sent to scroll region to scroll down 2 lines and put "New line..." at the bottom of tmux page.

OpenSSH:
```
\x1b[1;14r\x1b[2S\x1b[12;1H[INFO    ]  New line...  508 at time Tue Jun 11 05:41:57 2019\x1b[1;30r\x1b[14;1H
```

Mosh:
```
[0m[1;13r[?25l[13;1H

[r[12;1H[INFO    ]  New line...  118 at time Tue Jun 11 05:47:59 2019
```

**Comment by MaxRis** [comment] 2019-06-12 21:33
Screen record of the flickering issue:

![mosh-tmux-panes-flickering-issue](https://user-images.githubusercontent.com/1928902/59387802-bd1b9380-8d72-11e9-8b4f-f56f231370c0.gif)

**Comment by MaxRis** [comment] 2019-06-12 21:39
Source code of CPP application to continuously generate std output (used to repro the issue in above screen record):
```
#include <iostream>
#include <unistd.h>
#include <chrono>
#include <ctime>

int main()
{
    std::cout << "Launching std printer..." << std::endl;
    sleep(1);
    while(true) {
        static int counter = 0;
        std::time_t t = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
        std::cout << "[INFO    ]  New line...  " << ++counter << " at time " << std::ctime(&t) << std::endl;
        sleep(1);
        std::cout << "[INFO    ]  New line...  " << ++counter << std::ctime(&t) << std::endl;
        std::cout << "[INFO    ]  New line...  " << ++counter << std::ctime(&t) << std::endl;
        sleep(1);
    }
    return 0;
}
```
