### ISSUE TITLE
tab maint tweaks

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#105] opened 2019-05-30 13:29 UTC
The (x) only shows on a tab that's selected, that makes it annoying to close a bunch of tabs as you have to select each first. Could the (x) be made to show on hover over any tab?

Also, nice to have would be a close tabs to the left, close tabs to the right and close other options like other tabbed apps (Chrome/PyCharm/etc) have.

**Comment by mjs** [comment] 2019-06-03 22:47
I agree that showing the X on hover would be nice. I've just looked at number of Windows apps that use tabs (Visual Studio, Edge, Internet Explorer) and they handle the close button this way.

In the mean time, you can middle click on any tab to close it, even if it's not the currently focussed tab. This is consistent with most web browsers.

**Comment by felixse** [comment] 2019-06-04 03:07
I'm planning to replace the current hacked together tabs with the [Community Toolkit TabView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview) in the near future. This should solve this.

**Comment by peske** [comment] 2019-06-17 17:37
@felixse , do you need help with implementing the [Community Toolkit TabView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview)?

**Comment by mjs** [comment] 2019-07-30 00:14
This is now basically a duplicate of #109

**Closed** 2019-07-30 00:14 UTC
Labels: duplicate, enhancement, upstream

**Comment by cjw296** [comment] 2019-07-30 02:58
Does that include the (x)?

**Comment by mjs** [comment] 2019-07-30 09:44
@cjw296 I've moved the two things you've requested around tab closing to #160 and #161
